### ISSUE TITLE
Bug: v1.6.2 界面错误

### ISSUE THREAD

**Issue by yunkuangao** [koishijs/webui#125]
### 发生了什么?

我升级到v1.6.2，webui界面没有市场

### 哪个版本？

我用v1.6.2和v1.6.1做了对比，错误只在v1.6.2上发生

### 日志或者错误记录？

我发现了在浏览器的console里面出现了

v1.6.2版本:

![image](https://user-images.githubusercontent.com/40163747/224880457-27413aa6-9877-4d9c-be4f-79933af29772.png)

v1.6.1版本:

![image](https://user-images.githubusercontent.com/40163747/224880607-3c963e1f-3ca1-47ca-ad52-ecfef0b3479b.png)

### 附上我的配置

另外，我的整个代理是 cloudflare + traefik + docker

v1.6.2
```yaml
version: '3'
services:
  koishi:
    image: koishijs/koishi:v1.6.2-puppeteer
    container_name: koishi
    environment:
      TZ: Asia/Shanghai
    restart: always
    volumes:
      - $PWD/koishi:/koishi
    labels:
      - traefik.http.routers.koishi.rule=Host(`bot.example.org`)
      - traefik.http.routers.koishi.entrypoints=https
      - traefik.http.routers.koishi.tls.certresolver=letsencrypt
      - traefik.http.services.koishi.loadbalancer.server.port=5140
    networks:
      - traefik
networks:
  traefik:
    external: true
```

v1.6.1
```
version: '3'
services:
  koishi-test:
    image: koishijs/koishi:v1.6.1-puppeteer
    container_name: koishi-test
    environment:
      TZ: Asia/Shanghai
    restart: always
    volumes:
      - $PWD/koishi:/koishi
    labels:
      - traefik.http.routers.koishi-test.rule=Host(`bot-test.example.org`)
      - traefik.http.routers.koishi-test.entrypoints=https
      - traefik.http.routers.koishi-test.tls.certresolver=letsencrypt
      - traefik.http.services.koishi-test.loadbalancer.server.port=5140
    networks:
      - traefik
networks:
  traefik:
    external: true
```
