### ISSUE TITLE
Bug: 当配置存在 $if 时 在配置页面拖动配置 会报错

### ISSUE THREAD

**Issue by 502647092** [koishijs/webui#249]
### Describe the bug

当配置存在 $if 时 在配置页面拖动配置会报错 并且配置保存失败(没有写入文件
当拖动正常配置时 会恢复之前的状态

开发环境未复现 生产环境复现

相关配置区域
```
  group:develop:
    $if: env.NODE_ENV === 'development'
    server:tmhcza:
      path: ''
      token: '123456'
    hmr:
      root: .
```

错误日志
```
2023-10-19 10:23:02 [E] loader TypeError: Cannot read properties of undefined (reading 'ctx')
                            at _ConfigWriter.resolve (/koishi/node_modules/@koishijs/plugin-config/lib/shared/index.js:224:59)
                            at _ConfigWriter.unload (/koishi/node_modules/@koishijs/plugin-config/lib/shared/index.js:270:35)
                            at ctx.console.addListener.authority (/koishi/node_modules/@koishijs/plugin-config/lib/shared/index.js:180:27)
                            at WebSocket.receive (/koishi/node_modules/@koishijs/console/lib/index.js:143:45)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Steps to reproduce

![f238ad9614234ab3bf45164e084f179d](https://github.com/koishijs/koishi/assets/10203793/77e51c05-7e1b-4ed2-894d-f6312d1c369b)

### Expected behavior

正常处理配置

### Versions

System:
    OS: Linux 3.10 Alpine Linux

Binaries:
    Node: 18.17.1
    Yarn: 3.6.2

Koishi:
    Core: 4.15.1
    Console: 5.16.1
