### ISSUE TITLE
Bug: webui跳转到插件市场时不会刷新搜索项

### ISSUE THREAD

**Issue by borraken** [koishijs/webui#85]
### Describe the bug

当第二次跳转至插件市场时，不会触发新的搜索

### Steps to reproduce

新建docker容器，并使用旧的koishi.yml
插件配置中会有部分插件提示：此插件尚未安装，点击前往插件市场。
点击 ‘点击前往插件市场’ 
第一次成功，第二次后不会搜索，需要手动刷新页面
地址栏中keyword会有变更，但页面无反应

### Expected behavior

每次跳转至插件市场时都将正常触发搜索
（或者有根据koishi.yml快速从市场安装依赖的功能）
（docker怎么悄咪咪把配置文件位置改了，也没个文档）

### Versions

- OS: Linux Synology_bork 4.4.180+ docker koishi:v1.5.3-puppeteer
- Platform: 
- Node version: 
- Koishi version: 4.11.2

**Comment by HuanLinMaster** [comment]
不是很看得懂什么叫「使用旧的koishi.yml」，「第二次后不会搜索」的第二次指的是什么

**Comment by HuanLinMaster** [comment]
意思是 将一个非默认的 ```koishi.yml``` 复制到容器 ```/koishi``` 然后插件配置内就会出现 「此插件尚未安装，点击前往插件市场」
点击后跳转到market然后什么都不做 返回插件配置 再次点击不刷新？

**Comment by HuanLinMaster** [comment]
好像成功复现了 这是我的操作
```
yarn create koishi
koishi-test
n
n
```

进入目录 把koishi.yml改成这样

```yml
host: "127.0.0.1"
port: 5140
maxPort: 5149
plugins:
  group:basic:
    help: {}
    rate-limit: {}
    locales: {}
    commands: {}
    ~admin: {}
    ~bind: {}
  group:console:
    analytics: {}
    console:
      open: false
    dataview: {}
    desktop:
      $if: env.KOISHI_AGENT?.includes('Desktop')
    logger: {}
    insight: {}
    market:
      registry:
        endpoint: https://registry.npmmirror.com
      search:
        endpoint: https://registry.koishi.chat/index.json
    sandbox: {}
    status: {}
  group:database:
    database-sqlite: {}
    ~database-mysql: {}
    ~database-mongo: {}
    assets-local: {}
  group:adapter:
    adapter-onebot:
      selfId: '1302399374'
      token: ''
      protocol: ws
      endpoint: ws://马赛克:马赛克/onebot
    ~adapter-discord: {}
    ~adapter-telegram: {}
    ~adapter-kook: {}
    ~adapter-feishu: {}
    gocqhttp: {}
  video-parser:0kzt91:
    api: tenapi
  blockly:f9lneh: {}
  rr-image-censor:6wnjr3:
    offset: 65.99
  hlai-ocr:hrurk1: {}
  hlai-painter:ymh570: {}
  puppeteer:2oipri:
    headless: false
  epic-get-free-game:sryjb1: {}
  jiutian-toolkit:kxbq8q: {}
```

然后

```sh
yarn
yarn start
```

进入插件配置 找到 epic-get-free-game 插件 点击「此插件尚未安装，点击前往插件市场。」

等待跳转

点击搜索栏的 epic-get-free-game 回到插件配置 找到 epic-get-free-game 插件 点击「此插件尚未安装，点击前往插件市场。」

此时url是 ```http://127.0.0.1:5140/market?keyword=epic-get-free-game```

但是界面如图
![image](https://user-images.githubusercontent.com/94176676/212651951-2549f17e-99f3-45f0-b131-fe27532c1121.png)
